version: '3.1'
services:
  nginx:
    build: docker/nginx
    ports:
      - "8008:8008"
    depends_on:
      - nodejs
      - swagger
      - helpdocs
    volumes:
      - ./docker/nginx/development.conf:/etc/nginx/conf.d/default.conf
  nodejs:
    build: .
    ports:
     - "8888:8888"
    environment:
     - ISTEST=${ISTEST}
     - LDAP_URL=${LDAP_URL}
     - SEARCH_FILTER=${SEARCH_FILTER}
     - MUNIN_URL_SANDBOX=${MUNIN_URL_SANDBOX}
     - MUNIN_URL=${MUNIN_URL}
     - MIMER_URL_SANDBOX=${MIMER_URL_SANDBOX}
     - MIMER_URL=${MIMER_URL}
     - BASE_DN_LIST=${BASE_DN_LIST}
     - UPGRADE_TOOL_URL=${UPGRADE_TOOL_URL}
     - DTTADM100_USERNAME=${DTTADM100_USERNAME}
     - DTTADM100_PASSWORD=${DTTADM100_PASSWORD}
    depends_on:
     - mongodb
     - ldap
    volumes:
     - ./:/opt/mean.js
     - nodejs_node_modules:/opt/mean.js/node_modules
     - nodejs_public:/opt/mean.js/public
  mongodb:
    image: armdocker.seli.gic.ericsson.se/dockerhub-ericsson-remote/mongo:5.0.0
    ports:
     - '27018:27017'
    volumes:
     - mongodb_data:/data/db
     - mongodb_logs:/var/log/mongodb
  swagger:
    build:
      context: .
      dockerfile: docker/swagger/Dockerfile
    environment:
     - API_URL=/apidocs/swagger.json
  helpdocs:
    build:
      context: .
      dockerfile: docker/helpdocs/Dockerfile
    volumes:
     - ./helpdocs/help/en-us/helpdocs:/opt/helpdocs/help/en-us/helpdocs
  ldap:
    image: armdocker.seli.gic.ericsson.se/dockerhub-ericsson-remote/osixia/openldap:1.2.2

volumes:
  nodejs_node_modules:
  nodejs_public:
  mongodb_data:
  mongodb_logs:
